### ISSUE TITLE
Scala 2.12 milestones support

### ISSUE THREAD

**Issue by slandelle** [adamw/quicklens#25]
Hi @adamw 

Would it be possible to publish cross-built versions so projects depending on quicklens can give Scala 2.12 milestones a try, please?

Regards

**Comment by adamw** [comment]
Sure - maybe you could prepare a PR which cross-builds using 2.12?

**Comment by slandelle** [comment]
Here you are: #26

**Comment by adamw** [comment]
1.4.6 for 2.12 should be in central in 15-30 minutes

**Comment by slandelle** [comment]
You rock, thanks!

7 more other libs to go... ;-)
