### ISSUE TITLE
Is it possible to write custom modify wrappers that support .each, .at? 

### ISSUE THREAD

**Issue by bbarker** [adamw/quicklens#40]
This is probably my lack of knowledge of the macro system being an issue:

I have a method that looks like:

```scala
  def scModify[U](path: scala.Function1[SimulationConfig, U], cfgItem: U): Unit = {
    config match {
      case Some(sc) =>
        // TODO: add this to a more verbose logging level:
        println(s"Setting config's $path to $cfgItem")
        config = Option(sc.modify(path).setTo(cfgItem))

      case None => throw new RuntimeException("no SimulationConfig found for update!")
    }
  }
```

The idea is that:

1. Any object having access to the method is considered privileged (though I could make this more granular later if desired) so that it can modify the config.
2. Custom logging can be implemented when modifications take place.

When I try to use it where `.each` is involved like this:

```scala
  store.scModify(_.feedGroups.each.group, fg)
```

I get: 

```
Error:(27, 39) Reference to method each in class QuicklensEach should not have survived past type checking,
it should have been processed and eliminated during expansion of an enclosing macro.
          store.scModify(_.feedGroups.each.group, fg)
```

While I could easily write separate function wrappers that support `.each` and `.at` (though that does introduce some code duplication), it gets a bit complicated when you have more than one `.each`, `.at`, or both. Is there a workaround for this?

**Comment by adamw** [comment]
Unfortunately you cannot abstract over the path in a `.modify` call: the path must be statically known there to be processed by the macro at compile-time.

What you can do, however is the following:

`scModify((_: SimulationConfig).modify(_.feedGroups.each.group), fg)`

and the method definition would be sth like this:

`def scModify[U](lens: PathModify[SimulationConfig, U], cfgItem: U)`

Hope this helps!

**Comment by bbarker** [comment]
Thanks, that is quite slick! It looks like that solves the wrapper problem.

I plan to use something like ["friends"](https://stackoverflow.com/a/18634125/3096687) to  enforce whitelisting of classes that can use `scModify`, but using class strings instead to avoid needing to import all the packages into `scModify`'s scope.
