### ISSUE TITLE
Delete items in a List or Map

### ISSUE THREAD

**Issue by Tamriel** [adamw/quicklens#43]
How can I delete / remove items in a List or Map?

**Comment by adamw** [comment]
I think I would just modify the collection :) e.g. `something.modify(_.x.y.z.aCollection).using(_.filter(predicate))`

**Comment by Tamriel** [comment]
Can you give an example?

**Comment by adamw** [comment]
Sure:

```
case class Test1(c: List[Int])
case class Test2(t: Test1)

val z = Test2(Test1(List(10, 11, 12, 13, 14, 15)))
val z2 = z.modify(_.t.c).using(_.filter(_ % 2 == 0))
```

that will modify `z: Test2` and leave only even numbers on the list.

**Comment by Tamriel** [comment]
Thanks!
And how can I add an item?

**Comment by adamw** [comment]
```
z.modify(_.t.c).using(c => 25 :: c)
```

this will prepend 25 to the list.

**Comment by Tamriel** [comment]
Thank you very much!
