### ISSUE TITLE
upgrade to sbt-scalafmt 2.0?

### ISSUE THREAD

**Issue by SethTisue** [adamw/quicklens#54]
the Scalafmt version you're using is so old that it doesn't work in the Scala community build, so I had to do this: https://github.com/scalacommunitybuild/quicklens/commit/a265b2b7d9dc111d3818bb672b102e03f787aac2

the problem would go away if you upgraded to the latest

nbd, but would be nice

**Comment by adamw** [comment]
Done

**Comment by SethTisue** [comment]
thanks! https://github.com/scala/community-builds/commit/64943f8e6bd35b1a61b261dced32f35540507705
