### ISSUE TITLE
`.each` seems not to work in some nested contexts

### ISSUE THREAD

**Issue by benhutchison** [adamw/quicklens#6]
I think the following ought to work, but I get a compile error: `NestedEachExample.scala:11: value each is not a member of Iterable[String]`

(Inserting the implicit conversion by hand within the `modify(..)` expression isn't an option since it disrupts the macro.)

```scala
import com.softwaremill.quicklens._
object NestedEachExample extends App {
  implicit def quicklensIterable[A, B] = new QuicklensFunctor[Iterable, A, B] {
    def map(fa: Iterable[A])(f: A => B): Iterable[B] = fa.map(f)
  }
  case class NestedEach(items: Map[Int, String]) {
    def doModify = this.modify(_.items.values.each).setTo("Foo")
  }
}
```

**Comment by adamw** [comment]
The `.values` is the problem here: it's not a field in a case class, so generating a copy automatically (of only the values) is not possible. The error message is far from perfect, but I wouldn't expect this to work.

**Comment by benhutchison** [comment]
Ah, makes sense. So I should be updating the whole KV pair rather than
going straight to the values.

**Comment by adamw** [comment]
Yes, that should work I think.
