### ISSUE TITLE
Ability to index into list

### ISSUE THREAD

**Issue by zlangbert** [adamw/quicklens#8]
It would be cool to be able to replace an item in a list, e.g

```scala
modify(_: State)(_.someList(i)).setTo(???)
```

**Comment by adamw** [comment]
I think it's quite a specialized use-case, no? What would happen if the list doesn't have element `i`? I'm also afraid about enhancing the API as then you might as well have `head`, `tail` methods etc. :)

**Comment by zlangbert** [comment]
Specialized for sure. In my case I'm creating a list React elements dynamically and updating their state. I figure it would just throw a `NoSuchElementException` if it didn't exist. But I would understand not wanting to add this. It's not very safe.

**Comment by adamw** [comment]
Ok, I understand it might be useful, if somebody someday would like to create a PR, I'll be happy to accept :)

**Comment by OndrejSpanel** [comment]
If I am not mistaken, this is what `at` is doing now since commit 6dc71229bd0b9a5cb1780414a8483ca7f280c40d, and this issue can be closed now.

**Comment by adamw** [comment]
true, closing :)
